services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: oxigin-postgres-dev
    environment:
      POSTGRES_DB: oxigin_attendance
      POSTGRES_USER: oxigin_user
      POSTGRES_PASSWORD: oxigin_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oxigin_user -d oxigin_attendance"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend/OxiginAttendance.Api
      dockerfile: Dockerfile
    container_name: oxigin-backend-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=oxigin_attendance;Username=oxigin_user;Password=oxigin_dev_password"
      JwtSettings__SecretKey: "dev-super-secret-jwt-signing-key-that-is-at-least-32-characters-long-for-security-purposes"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:80"
    volumes:
      - ./backend/OxiginAttendance.Api:/app/source
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: oxigin-frontend-dev
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local